on:
  workflow_call:
  # Permissions inherited from caller workflow

permissions: {}

jobs:
  sslib-main:
    name: Test securesystemslib main branch (not a merge blocker)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout TUF
        uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4.1.5

      - name: Set up Python
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
        with:
          python-version: '3.x'
          cache: 'pip'
          cache-dependency-path: |
            requirements/*.txt
            pyproject.toml

      - name: Install dependencies
        run: |
          python3 -m pip install --constraint requirements/build.txt tox

      - name: Run tox
        run: tox -e with-sslib-main
